output_dir: results_variant_test
samplesheet: config/samples.tsv
metadata: config/metadata.tsv

run:
  mode: variant_only
  variant_data_mode: vcf_interpretation
  assay: dna
  read_type: short
  threads: 4
  use_external_variants_for_prs: true

reference:
  genome_build: GRCh38
  fasta: resources/reference/GRCh38.fa
  gtf: resources/reference/Homo_sapiens.GRCh38.110.gtf
  star_index: resources/reference/star_grch38_index

alignment:
  long_read_preset_dna: map-ont
  long_read_preset_rna: splice

thresholds:
  min_base_quality: 20
  min_read_length: 50
  min_variant_qual: 0
  min_variant_depth: 0
  require_filter_pass: false
  de_padj: 0.05
  de_abs_log2fc: 1.0
  enrichment_qvalue: 0.05
  variant_assoc_pvalue: 5e-8
  variant_assoc_abs_effect: 0.0
  variant_heatmap_top_n: 50

paths:
  variants_input: data/variants/test_small.vcf
  prs_weights: resources/prs/models/PGS002280.txt.gz
  gene_sets: resources/enrichment/real/Reactome_2022.gmt

prs:
  weights_format: pgs_catalog
  prefer_ds: true
  allow_ambiguous_strand: false

annotation:
  method: overlap
  snpeff_database: ""

deseq2:
  design_formula: "~ condition"
  contrast: "condition,case,control"
