output_dir: results_test_data_niagads_advp_ad_gwas_hg38

run:
  mode: variant_only
  variant_data_mode: gwas_summary
  assay: dna
  read_type: short
  threads: 4

reference:
  genome_build: GRCh38

paths:
  variants_input: test_data/niagads_advp_ad_gwas_hg38/niagads_advp_ad_variant_records_hg38.tsv
  prs_weights: ""
  gene_sets: resources/enrichment/real/Reactome_2022.gmt

validation:
  enforce_build_match: true
  fail_on_warning: false
