output_dir: results_test_data_giab_nist7035_fastq_subset_grch38
samplesheet: test_data/giab_nist7035_fastq_subset_grch38/samples.tsv
metadata: test_data/giab_nist7035_fastq_subset_grch38/metadata.tsv

run:
  mode: full
  assay: dna
  read_type: short
  threads: 4
  use_external_variants_for_prs: false
  enable_depth: false

reference:
  genome_build: GRCh38

alignment:
  dna_short_aligner: auto

paths:
  variants_input: ""
  prs_weights: ""
  gene_sets: resources/enrichment/real/Reactome_2022.gmt

validation:
  enforce_build_match: true
  fail_on_warning: false
